plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/jest"
hooks: {}
options:
  "@dotcom-tool-kit/circleci":
    nodeVersion:
      - '22.3-browsers'
      - '20.15-browsers'
      - '18.20-browsers'
